In [1]:
%matplotlib tk
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

In [2]:
def nbsum(spin):
    sum_i = 0
    for i in range(n):
        for j in range(n):
            sum_i += spin[(i-1)][j]*spin[i][j] + spin[(i+1)%n][j]*spin[i][j] + spin[i][(j-1)]*spin[i][j] + spin[i][(j+1)%n]*spin[i][j]    
    return sum_i


def h(spin,b,J,i,j):
    return -b*np.sum(spin)-J*(spin[(i-1)][j]*spin[i][j] + spin[(i+1)%n][j]*spin[i][j] + spin[i][(j-1)]*spin[i][j] + spin[i][(j+1)%n]*spin[i][j])

def H(spin,b,J,i,j):
    return -b*np.sum(spin)-J*nbsum(spin)

def spin_i(n):
    S_i = np.random.random(size=(n,n))
    for i in range(n):
        for j in range(n):
            if S_i[i][j] < 0.5: S_i[i][j] = -1
            if S_i[i][j] >= 0.5: S_i[i][j] = 1
    return S_i

def Ising(S_i,b,J,n):
    N = n*n
    for i in range(n):
        for j in range(n):
            if b==0:
            
                if S_i[i][j] == 1:
                    candidate = -1
                else:
                    candidate = 1

                dh = -J * (candidate - S_i[i][j]) * (S_i[(i+1)%n][j] + S_i[i-1][j] + S_i[i][(j+1)%n] + S_i[i][j-1])

                if dh < 0 or np.random.random() < np.exp(-dh):
                    S_i[i][j] = candidate
            else:
                S_n = np.random.random()
                if S_n < 0.5: S_n = -1
                if S_n >= 0.5: S_n = 1

                S_i2 = np.copy(S_i)
                S_i2[i][j] = S_n

                dh = h(S_i2,b,J,i,j)-h(S_i,b,J,i,j)

                if dh <= 0 or np.random.random() < np.exp(-dh): S_i[i][j] = S_n 

    M = np.sum(S_i)/N
    E = H(S_i,b,J,i,j)/N

    return S_i, M, E


In [10]:
b = 0.0
J = 0.7
sweeps = 100
n = 64

M_tot = np.array([])
E_tot = np.array([])
S_array = np.array([])
S_0 = spin_i(n)
ims = []
fig = plt.figure()
ev = 0

for k in range(sweeps):
    if k == 0: S, M_0, E_0 = Ising(S_0,b,J,n)
    else: 
        S_i, M_i, E_i = Ising(S,b,J,n)
        
        M_tot = np.append(M_tot,M_i)
        E_tot = np.append(E_tot,E_i)
        S = np.copy(S_i)
      #  S_array = np.append(S_array,S)
        
        im = plt.imshow(S, animated=True, cmap="Greys")
        ims.append([im])
        
    if k%(sweeps/10)==0:
        ev += 10
        print("Process:",ev,"%")

m_avg = np.sum(M_tot)/sweeps
e_avg = np.sum(E_tot)/sweeps
print(m_avg,e_avg)

ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
#ani.save('Ising_model4.gif', writer="pillow")
plt.show()
    

Process: 10 %
Process: 20 %
Process: 30 %
Process: 40 %
Process: 50 %
Process: 60 %
Process: 70 %
Process: 80 %
Process: 90 %
Process: 100 %
0.67755859375 -2.598544921875


In [30]:
b = 0.0
J = 0.5
sweeps = 100
n = 32
fig = plt.figure()

ims = Animate(b,J,sweeps,n)
ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True,
                                   repeat_delay=1000)

-0.66173828125 -1.5460546875


In [60]:
plt.plot(lin,M_tot,"-")
print(S_array)

[]


In [61]:
plt.plot(lin,E_tot)

In [24]:
s = spin_i(3)
print(s)

[[ 1 -1 -1]
 [ 1 -1  1]
 [-1  1  1]]


In [66]:
plt.show()

In [135]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [152]:
n=4
print(nbsum(a))

tmp= 17 i= 1 5 j= 1 2
tmp= 15 i= 1 6 j= 2 3
tmp= 17 i= 1 7 j= 3 4
tmp= 19 i= 1 8 j= 0 1
tmp= 9 i= 2 9 j= 1 6
tmp= 7 i= 2 10 j= 2 7
tmp= 9 i= 2 11 j= 3 8
tmp= 11 i= 2 12 j= 0 5
tmp= 17 i= 3 13 j= 1 10
tmp= 15 i= 3 14 j= 2 11
tmp= 17 i= 3 15 j= 3 12
tmp= 19 i= 3 16 j= 0 9
tmp= 25 i= 0 1 j= 1 14
tmp= 23 i= 0 2 j= 2 15
tmp= 25 i= 0 3 j= 3 16
tmp= 27 i= 0 4 j= 0 13
2584


In [114]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9
